/**
 * Generated by scripts/build-showcase.ts — do not edit by hand.
 *
 * The Highcharts modules the showcase needs, and the capability declaration the agent is given.
 * Both come from the chart-type declaration, so a type that needs a module imports it here
 * automatically, and the app never claims to draw something its bundle cannot render.
 */
import 'highcharts/modules/heatmap';
import 'highcharts/modules/coloraxis';

export const showcaseCapabilities: readonly string[] = ['bar', 'line', 'spline', 'area', 'areaspline', 'pie', 'heatmap'];
