/**
 * Where the boundary is.
 *
 * The question a reader actually has is "can I use this for my charts?", and the honest answer
 * is a list of what it cannot do yet — not a footnote in a roadmap. So the shapes with no
 * declared type, and the shapes the compiler refuses today, are on the page with the data they
 * would need and what each one is waiting for.
 *
 * Every row here is a corpus case, generated by `scripts/build-showcase.ts`. When a shape moves
 * from this list to the one above, the diff says so.
 */
import { Badge, Disclosure, Field, Table } from '../ui.tsx';
import { showcase } from '../showcase.ts';

export function BoundarySection() {
  return (
    <div>
      {showcase.boundary.map((one) => {
        const rows = one.data.rows.length;
        const refused = one.reason.kind === 'refused';

        return (
          <article
            key={one.id}
            style={{
              border: '1px solid #e6d9a8',
              borderRadius: 10,
              padding: '14px 18px 16px',
              marginBottom: 16,
              background: '#fffdf5',
            }}
          >
            <header style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
              <Badge tone="bad">{refused ? 'refused today' : 'no type yet'}</Badge>
              <code style={{ fontSize: 12, color: '#555' }}>
                {one.data.name} · {rows} {rows === 1 ? 'row' : 'rows'}
              </code>
              <span style={{ marginLeft: 'auto', fontSize: 12, color: '#666' }}>
                shapes it serves: {one.data.shapes.join(', ')}
              </span>
            </header>

            <Field label="Would be asked as">{one.query}</Field>
            <Field label="Expected">{one.expects}</Field>
            <Field label="Why it is not drawn above">
              {refused ? (
                <>
                  The compiler refuses this spec, and its message says why:{' '}
                  <em>{one.reason.detail}</em>
                </>
              ) : (
                one.reason.detail
              )}
            </Field>

            {one.nearlyWorks ? (
              <Field label="The nearest thing that does work">
                It compiles — and costs you <strong>{one.nearlyWorks.loses}</strong>. Nothing is renamed or defaulted;
                the column is simply absent from the output.
              </Field>
            ) : null}

            <Field label="What the data stresses">{one.data.why}</Field>

            <Disclosure summary={`The ${rows} ${rows === 1 ? 'row' : 'rows'} it would run on`}>
              <Table input={one.data.rows} />
            </Disclosure>
          </article>
        );
      })}
    </div>
  );
}
